Need to added python dependency back on to resolve Error.
Error: An exception occurred within a child process:
  FormulaUnknownPythonError: The version of Python to use with the virtualenv in the `glennbrown/tap/certbot-dns-cloudflare` formula
cannot be guessed automatically because a recognised Python dependency could not be found.

If you are using a non-standard Python dependency, please add `:using => "python@x.y"`
to 'virtualenv_install_with_resources' to resolve the issue manually.